// firebase-login/src/views/HomeView.vue
<template>
  <div class="home">
    <h2>This is the main page. I got here via {{byWayOf}}</h2>
    <p>{{userInfo}}</p>
    <img :src="userPhotoURL" v-if="userPhotoURL.length > 0" width="64">
    <button @click="outtahere">Logout</button>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import {
  getAuth,
  onAuthStateChanged,
  User,
  Auth,
  signOut,
} from "firebase/auth";
@Component
export default class HomeView extends Vue {
  @Prop() readonly byWayOf!: string;

  userPhotoURL = "";
  auth: Auth | null = null;
  userInfo = "";
  mounted(): void {
    this.auth = getAuth();
    onAuthStateChanged(this.auth, (user: User | null) => {
      console.log("Auth changed", user);
      if (user) {
        this.userPhotoURL = user.photoURL ?? "";
        this.userInfo = `${user.displayName ?? "No Name"}`;
      }
    });
  }

  outtahere(): void {
    if (this.auth) signOut(this.auth);

    // Back to the previous page
    this.$router.back();
  }
}
</script>

// firebase-login-react/src/views/HomeView.tsx
import { getAuth, onAuthStateChanged, signOut } from "firebase/auth";
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Auth, User } from "firebase/auth";

let auth: Auth | null;

export default function (props: any): JSX.Element {
  const navigate = useNavigate();
  const { byWayOf } = useParams();
  const [userPhotoURL, setPhotoURL] = useState("");
  const [userName, setUserName] = useState("");

  useEffect(() => {
    auth = getAuth();
    onAuthStateChanged(auth, (user: User | null) => {
      if (user) {
        setPhotoURL(user.photoURL ?? "");
        setUserName(user.displayName ?? "No name");
      } else {
        setPhotoURL("");
        setUserName("");
      }
    });
  }, []);

  async function outtahere() {
    if (auth) await signOut(auth);
    setPhotoURL("");
    navigate(-1);
  }

  return (
    <>
      <h2>Home View</h2>
      <p>
        Logged in via {byWayOf} {userName}
      </p>
      {userPhotoURL.length > 0 ? <img src={userPhotoURL} /> : <></>}
      <div>
        <button onClick={outtahere}>Logout</button>
      </div>
    </>
  );
}
function useHistory() {
  throw new Error("Function not implemented.");
}
