// vue3-basics/src/components/20-forloop.vue
<template>
  <h2>Chemical Elements</h2>
  <ol>
    <li v-for="(a, pos) in atoms" :key="pos">{{ a }}</li>
  </ol>
</template>


<script setup lang="ts">
import { ref } from "vue";

const atoms = ref([
  "Argon",
  "Barium",
  "Carbon",
  "Erebium",
  "Fluor",
  "Galium",
  "Helium",
  "...and more...",
]);
</script>

// react-basics/src/functional-components/20-forloop.tsx
import { useState } from "react";
interface Atom {
  name: string;
  weight: number;
}
const chemData: Atom[] = [
  { name: "Argon", weight: 39.948 },
  { name: "Barium", weight: 137.33 },
  { name: "Carbon", weight: 12.011 },
  { name: "Fluor", weight: 19.998 },
  { name: "Galium", weight: 69.723 },
  { name: "Helium", weight: 4.0024 },
];

export default function Sample(): JSX.Element {
  const [elements] = useState(chemData);

  return (
    <>
      <p>Chemical Elements (Functional)</p>
      <ul>
        {elements.map((e: Atom, pos: number) => (
          <li key={pos}>
            {e.name} ({e.weight} daltons)
          </li>
        ))}
      </ul>
      {elements.map((e: Atom) => (
        <>
          <h2>Chemical element {e.name}</h2>
          <p>Atomic weight is {e.weight} AMUs</p>
        </>
      ))}
    </>
  );
}
