// vue3-basics/src/components/20-forloop.vue
<template>
  <h2>Chemical Elements</h2>
  <ol>
    <li v-for="(a, pos) in atoms" :key="pos">{{ a }}</li>
  </ol>
</template>


<script setup lang="ts">
import { ref } from "vue";

const atoms = ref([
  "Argon",
  "Barium",
  "Carbon",
  "Erebium",
  "Fluor",
  "Galium",
  "Helium",
  "...and more...",
]);
</script>

// react-basics/src/class-components/20-forloop.tsx
import { Component } from "react";
type Atom = {
  name: string;
  weight: number;
};
type MyState = {
  elements: Atom[];
};
const chemData: Atom[] = [
  { name: "Argon", weight: 39.948 },
  { name: "Barium", weight: 137.33 },
  { name: "Carbon", weight: 12.011 },
  { name: "Fluor", weight: 19.998 },
  { name: "Galium", weight: 69.723 },
  { name: "Helium", weight: 4.0024 },
];

export default class Sample extends Component<any, MyState> {
  state = {
    elements: chemData,
  };

  render(): JSX.Element {
    return (
      <>
        <p>Chemical Elements (Class-based)</p>
        <ul>
          {this.state.elements.map((e: Atom, pos: number) => (
            <li key={pos}>
              {e.name} ({e.weight} daltons)
            </li>
          ))}
        </ul>
      </>
    );
  }
}
